'use strict';class g{constructor(a){this.message=a}toString(){return this.message}}class h extends g{}function k(a){return a.g.pop()||null}function l(a,b){a.g.push(b.bind(a))}class m{constructor(){this.g=[]}}class n extends m{constructor(){super();this.j=new Map}}class p{get value(){}set value(a){}bind(){}}class q extends p{constructor(a,b){super();this.name=a;this.g=b}get value(){return this.g.j.get(this.name)??0}set value(a){this.g.j.set(this.name,a)}bind(){return new q(this.name,this.g)}}
class r extends p{constructor(a){super();this.g=a}get value(){return this.g}set value(a){throw new g("You can't set a value to a literal");}bind(){return this}}class t{constructor(a,b,c,d){this.g=a;this.i=b;this.l=c;this.h=d}}
const v=new Map([new t("add","+",(a,b)=>{l(b,new r(k(b).value+k(b).value))}),new t("subtract","-",(a,b)=>{l(b,new r(-k(b).value+k(b).value))}),new t("multiply","*",(a,b)=>{l(b,new r(k(b).value*k(b).value))}),new t("divide","/",(a,b)=>{a=k(b).value;const c=k(b).value;l(b,new r(c/a))}),new t("power","**",(a,b)=>{a=k(b).value;const c=k(b).value;l(b,new r(c**a))}),new t("number",null,(a,b)=>{l(b,new r(a.value))},a=>{const b=new u(a.g);b.value=parseInt(a.value,10);return b}),new t("identifier",null,(a,
b)=>{l(b,new q(a.value,b))}),new t("assign","=",(a,b)=>{a=k(b).value;k(b).value=a;l(b,new r(a))}),new t("openBracket","("),new t("closeBracket",")")].map(a=>[a.g,a])),w=Array.from(v.values()).filter(a=>null!=a.i).reduce((a,b)=>{const c=b.i[0];let d=a.get(c);d||a.set(c,d=[]);d.push(b);return a},new Map);class x{constructor(a){this.h=a}get g(){return this.h}}function y(a){var b=v.get(a.h);b.h?a=b.h(a):(b=new u(a.g),b.value=a.value,a=b);return a}
class z extends x{constructor(a){super(a);this.value=null}toString(){return`${this.h.toString()}(${this.value||""})`}}class u extends x{constructor(a){super(a);this.value=null}toString(){return`${this.h.toString()}${null!==this.value?" ":""}${this.value??""}`}}const A=new Map([["number",/(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/y],["identifier",/[_a-zA-Z][_a-zA-Z0-9]*/y]]);
function*C(a){const b=a.length;for(let e=0;e<b;++e){var c=a[e];if(" "!==c){c=w.get(c);if(c){var d=null;for(let f of c)f.i&&a.startsWith(f.i,e)&&(!d||d.i.length<f.i.length)&&(d=f);c=d}else c=null;if(c)yield new z(c.g),e+=c.i.length-1;else{c=!1;for(let f of A.keys())if(d=A.get(f),d.lastIndex=e,d=d.exec(a)){c=!0;d=d[0];const B=new z(f);B.value=d;yield B;e+=d.length-1;break}if(!c)throw new h(`Found a strange character in the source at ${e}: ${a[e]}`);}}}}
function D(a,b,c,d,e){if(a.g)d=D(a.g,b,c,d);else{{const f=c[d];if("openBracket"===f.g){if(d=D(E,b,c,d+1),"closeBracket"!=c[d].g)throw new h("Ouch, no closing bracket");}else"identifier"!==f.g&&("subtract"===f.g&&++d,f.value=`${"subtract"==f.g?"-":""}${c[d].value}`),b.push(y(f));d+=1}}e&&b.push(y(e));d<c.length?a.h.has(c[d].g)?(e=c[d],a=D(a,b,c,d+1,e)):a=d:a=d;return a}function F(a,b){return new G(b,a)}class G{constructor(a,b){this.g=b||null;this.h=new Set(a)}}
const E=F(F(F(new G(["power"]),["multiply","divide"]),["add","subtract"]),["assign"]);class H{constructor(a){this.g="string"===typeof a?[]:Array.from(a);"string"===typeof a&&(a=Array.from(C(a)),D(E,this.g,a,0))}toString(){return this.g.join("\n")}}const I=new n,J=document.querySelector("#results");function K(a){const b=document.createRange();b.selectNodeContents(a.currentTarget);a=window.getSelection();a.removeAllRanges();a.addRange(b)}
function L(a){const b=document.createElement("div");b.textContent=String(a);b.addEventListener("click",K);return b}document.querySelector("#inputLine").addEventListener("keydown",a=>{if("Enter"===a.key){var b=a.currentTarget.value;const f=L(b);f.classList.add("q");b=new H(b);console.log(b.toString());var c=b;b=I||new n;for(e of c.g){c=e;var d=b;v.get(c.h).l(c,d)}var e=k(b).value;I.j.set("last",e);e=L(e);e.classList.add("a");J.append(f,e);a.currentTarget.select()}});
