Object.defineProperty(self,"CalculateCore",{value:(()=>{function*E(a){const b=a.length;for(let e=0;e<b;++e){var c=a[e];if(" "!==c){c=F.get(c);if(c){var d=null;for(let h of c)h.m&&a.startsWith(h.m,e)&&(!d||d.m.length<h.m.length)&&(d=h);c=d}else c=null;if(c)yield new r(c.g),e+=c.m.length-1;else{c=!1;for(let h of t.keys())if(d=t.get(h),d.lastIndex=e,d=d.exec(a)){c=!0;d=d[0];const u=new r(h);u.value=d;yield u;e+=d.length-1;break}if(!c)throw new v(`Found a strange character in the source at ${e}: ${a[e]}`,
a,e);}}}}function f(a,b){return(...c)=>b.apply(a,c)}function w(a){let b={execute:f(self,c=>a.C(c[m])),optimize:f(self,()=>w(a.G())),toString:f(self,()=>a.toString())};Object.defineProperty(b,"numOpcodes",{get:f(self,()=>a.D),enumerable:!0});Object.defineProperty(b,m,{value:a});return Object.freeze(b)}class x{constructor(a){this.message=a}toString(){return this.message}}class v extends x{constructor(a,b,c){super(a);this.offset=c}}class y{constructor(){this.h=[]}j(){return this.h.pop()||null}g(a){this.h.push(a.bind(this))}}
class z extends y{constructor(){super();this.i=new Map}u(a){return this.i.get(a)}s(a,b){this.i.set(a,b)}v(){this.i.clear()}B(a){for(let b of a.entries())this.s(b[0],b[1])}}class G extends y{constructor(){super();this.o=[];this.i=!1}u(){this.i=!0;return 1}s(){this.i=!0}v(){this.i=!0}B(){this.i=!0}j(){const a=super.j();a&&this.o.push(a);return a}g(a){this.i&&(a=new n("**unknown**",this),this.i=!1);this.o.length=0;super.g(a)}get F(){return this.h.length}get H(){return!!this.h.length}get l(){return this.A instanceof
k}get J(){return this.A.value}I(a){return this.h.slice(a)}get A(){return this.h[this.h.length-1]}}class A{get value(){}set value(a){}g(){}bind(){}}class n extends A{constructor(a,b){super();this.name=a;this.h=b}get value(){return this.h.u(this.name)??0}set value(a){this.h.s(this.name,a)}g(){const a=new l("identifier");a.value=this.name;return a}bind(){return new n(this.name,this.h)}}class k extends A{constructor(a){super();this.h=a}get value(){return this.h}set value(a){throw new x("You can't set a value to a literal");
}g(){const a=new l("number");a.value=this.h;return a}bind(){return this}}class g{constructor(a,b,c,d){this.g=a;this.m=b;this.i=c;this.h=d}l(a){if(this.h)return this.h(a);const b=new l(a.g);b.value=a.value;return b}}const H=[new g("add","+",(a,b)=>{b.g(new k(b.j().value+b.j().value))}),new g("subtract","-",(a,b)=>{b.g(new k(-b.j().value+b.j().value))}),new g("multiply","*",(a,b)=>{b.g(new k(b.j().value*b.j().value))}),new g("divide","/",(a,b)=>{a=b.j().value;const c=b.j().value;b.g(new k(c/a))}),new g("power",
"**",(a,b)=>{a=b.j().value;const c=b.j().value;b.g(new k(c**a))}),new g("number",null,(a,b)=>{b.g(new k(a.value))},a=>{const b=new l(a.g);b.value=+a.value;return b}),new g("identifier",null,(a,b)=>{b.g(new n(a.value,b))}),new g("assign","=",(a,b)=>{a=b.j().value;b.j().value=a;b.g(new k(a))}),new g("openBracket","("),new g("closeBracket",")")],p=new Map(H.map(a=>[a.g,a])),F=Array.from(p.values()).filter(a=>null!=a.m).reduce((a,b)=>{const c=b.m[0];let d=a.get(c);d||a.set(c,d=[]);d.push(b);return a},
new Map);class B{constructor(a){this.h=a}get g(){return this.h}}class r extends B{constructor(a){super(a);this.value=null}toString(){return`${this.h.toString()}(${this.value||""})`}i(){return p.get(this.h).l(this)}}class l extends B{constructor(a){super(a);this.value=null}toString(){return`${this.h.toString()}${null!==this.value?" ":""}${this.value??""}`}i(a){p.get(this.h).i(this,a)}}const t=new Map([["number",/(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?/y],["identifier",/[_a-zA-Z][_a-zA-Z0-9]*/y]]);
class C{constructor(a,b){this.i=b||null;this.o=new Set(a)}l(a,b,c){let d;return this.o.has(b[c].g)?(d=b[c],this.g(a,b,c+1,d)):c}g(a,b,c,d){if(this.i)c=this.i.g(a,b,c);else{const e=b[c];if("openBracket"===e.g){if(c=D.g(a,b,c+1),"closeBracket"!=b[c].g)throw new v("Ouch, no closing bracket");}else"identifier"!==e.g&&("subtract"===e.g&&++c,e.value=`${"subtract"==e.g?"-":""}${b[c].value}`),a.push(e.i());c+=1}d&&a.push(d.i());return c<b.length?this.l(a,b,c):c}h(a){return new C(a,this)}}const D=(new C(["power"])).h(["multiply",
"divide"]).h(["add","subtract"]).h(["assign"]);class q{constructor(a){this.g="string"===typeof a?[]:Array.from(a);if("string"===typeof a){var b=this.g;a=Array.from(E(a));D.g(b,a,0)}}C(a){a=a||new z;for(let b of this.g)b.i(a);return a.j().value}G(){const a=new G;var b=[];let c=0,d=null;for(let e of this.g)a.H&&a.l?d=a.I(c):d=null,e.i(a),a.l||(null!=d&&d.g&&b.push(...d.map(h=>h.g())),b.push(e),c=a.F);return a.l?(b=new l("number"),b.value=a.J,new q([b])):b.length<this.g.length?new q(b):this}get D(){return this.g.length}toString(){return this.g.join("\n")}}
const m=Symbol();return{newContext:f(self,function(){let a=new z,b={getRegister:f(self,c=>a.u(c)),setRegister:f(self,(c,d)=>{a.s(c,d)}),setRegisters:f(self,c=>{a.B(c)}),clearRegisters:f(self,()=>{a.v()}),toString:f(self,()=>a.toString())};Object.defineProperty(b,m,{value:a});return Object.freeze(b)}),newProgram:f(self,function(a){return w(new q(a))})}})()});
